### ISSUE TITLE
Modify Mesh on runtime

### ISSUE THREAD

**Issue by FlopCoat** [azixMcAze/Unity-UIGradient#2]
Hey, awesome asset, but I have stumbled upon a problem, how to use the ModifyMesh (VertexHelper vh) function in runtime? How do I get the vh value?

Thanks

**Comment by azixMcAze** [comment]
Hi!

You don't have to use this method, it is and internal method. You just have to add the component to your UI GameObjects

**Comment by FlopCoat** [comment]
I get that, but how do I apply for ex. the corner gradient component color variables in runtime? If I change the gradient color variables, they change, but the changes doesn't get applied to the actual image. Hence I need to call the ModifyMesh (); function, or is there another way to apply the changes?

**Comment by azixMcAze** [comment]
My bad!

You can call `SetVerticesDirty()` on the `Graphic` component (`Text` or `Image` for example) on the same `GameObject` as the `UIGradient` script.

You can also add this method to the `UIGradient` script:
```
    public void SetDirty()
    {
        graphic.SetVerticesDirty();
    }
```

**Comment by FlopCoat** [comment]
That did the trick, thank you!
