### ISSUE TITLE
Any way to force update the gradient?

### ISSUE THREAD

**Issue by NALStudio** [azixMcAze/Unity-UIGradient#4]
Is there any way to forcefully update the gradient if I change the colours at runtime?

**Comment by azixMcAze** [comment]
Hi,

There is no method in UI gradient to update the gradient but you can set the `Graphic` component(`UI.Image`  or `UI.Text` for example) dirty to force the update:
```csharp
var graphics = GetComponent<Graphic>();
graphic.SetVerticesDirty();
```

**Comment by NALStudio** [comment]
Oh, thanks!
